#!/usr/bin/env bash
# install.sh
# build and install presshold as a systemd user service.
set -euo pipefail

BIN_DIR="$HOME/.local/bin"
SERVICE_DIR="$HOME/.config/systemd/user"
ENV_DIR="$HOME/.config/presshold"
BINARY="$BIN_DIR/presshold"

# ── Build ─────────────────────────────────────────────────────────────────────
echo "==> Building presshold (release)…"
cargo build --release

# ── Install binary ────────────────────────────────────────────────────────────
mkdir -p "$BIN_DIR"
install -m 755 target/release/presshold "$BINARY"
echo "    Installed: $BINARY"

# ── Environment file ──────────────────────────────────────────────────────────
# The systemd user instance does not always inherit DISPLAY / WAYLAND_DISPLAY.
# We write a small env file that the service unit reads via EnvironmentFile=.
mkdir -p "$ENV_DIR"
{
  echo "# Auto-generated by install.sh. Re-run if you switch display servers."
  [[ -n "${DISPLAY:-}"          ]] && echo "DISPLAY=$DISPLAY"
  [[ -n "${WAYLAND_DISPLAY:-}"  ]] && echo "WAYLAND_DISPLAY=$WAYLAND_DISPLAY"
  [[ -n "${XDG_RUNTIME_DIR:-}"  ]] && echo "XDG_RUNTIME_DIR=$XDG_RUNTIME_DIR"
  [[ -n "${DBUS_SESSION_BUS_ADDRESS:-}" ]] && echo "DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS"
  echo "RUST_LOG=${RUST_LOG:-info}"
} > "$ENV_DIR/env"
echo "    Environment: $ENV_DIR/env"

# ── systemd user service ──────────────────────────────────────────────────────
mkdir -p "$SERVICE_DIR"
cp presshold.service "$SERVICE_DIR/presshold.service"
echo "    Service unit: $SERVICE_DIR/presshold.service"

systemctl --user daemon-reload
systemctl --user enable presshold.service
systemctl --user restart presshold.service

echo ""
echo "==> presshold installed and started."
echo ""

# ── Input group check ─────────────────────────────────────────────────────────
if ! groups | grep -qw input; then
  echo "⚠  Your user is NOT in the 'input' group."
  echo "   presshold needs raw device access to intercept keyboard events."
  echo "   Fix with:"
  echo "     sudo usermod -aG input \$USER"
  echo "   Then log out and back in, and re-run:"
  echo "     systemctl --user restart presshold.service"
fi
